configfile: "scripts/config/config.yaml",

rule all:
     input:
        expand("tmp/{sample}.fastq", sample = config["samples"]),
        expand("tmp/{sample}.fastq", sample = config["samples"])
 
rule unzip:
     input:
        "data/subset/{sample}.fastq.gz"
     output:
        temp("tmp/{sample}.fastq")
     shell:
        """
        mkdir -p tmp
        gunzip -c {input} > {output}
        """
